Show more skills
tighten/onramp pull request #485
Opened 2022-10-09 16:36 UTC by LubosGangster

sorry it took me so long, couldn't done it sooner than today, cause i was busy

2022-10-11 17:05 UTC, TammyTee requested changes
Hi @LubosGangster!

Thanks for working on this. I wonder if we might be able to take a much simpler approach to achieve this by using [AlpineJS](https://alpinejs.dev/start-here) (already included in the codebase) to show/hide extra skills right on the frontend. 

Would you mind looking into that and let me know what you think? Thanks!

2022-10-17 12:51 UTC, TammyTee commented
Hi @LubosGangster - is there anything I can help you with here?

2022-10-23 14:37 UTC, LubosGangster commented
Hi, @TammyTee , yes you are right, thanks for the review. I have not heard of alpine js until now. I repaired it.

2022-10-25 19:21 UTC, TammyTee approved these changes
LGTM 🎉 - I just included two small suggestions to fix code indentation but this looks and works great otherwise! Thank you!

2022-10-25 19:21 UTC, TammyTee commented on resources/views/modules/show.blade.php
>                                  :init-completed="{{ $completedSkills->contains($skill->id) ? 'true' : 'false' }}"
```suggestion
                                    :init-completed="{{ $completedSkills->contains($skill->id) ? 'true' : 'false' }}"
```

2022-10-25 19:21 UTC, TammyTee commented on resources/views/modules/show.blade.php
> +                                ></skill>
```suggestion
                                <skill x-show="showMore"
                                   @if (Auth::check() && Auth::user()->hasTrack() && Auth::user()->track->modules->contains($module->id)) :completable="true" @else :completable="false" @endif
                                   :init-completed="{{ $completedSkills->contains($skill->id) ? 'true' : 'false' }}"
                                   id="{{ $skill->id }}"
                                   text="{{ $skill->name }}"
                                   type="{{ $skill->getMorphClass() }}"
                                ></skill>
```

2022-10-25 19:22 UTC, TammyTee commented on app/Models/Module.php
> +
```suggestion
```

2022-10-25 19:24 UTC, merged